print("###############################")
print("#                             #")
print("#   Muhammad Rizki Ramadhan   #")
print("#        2310817310008        #")
print("#                             #")
print("###############################")
